spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/news-portal-g-48"
    username: "postgres"
    password: "1823"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5000
      driver-class-name: "org.postgresql.Driver"

client:
  newsapi:
    properties:
      api-key: "f1c821175ea64a5c82b4f17151925c25"
      base-url: "https://newsapi.org"

